### ISSUE TITLE
Request for adding W bond-orientational order parameters

### ISSUE THREAD

**Issue by narendra8995** [pyscal/pyscal#88] opened 2020-11-19 19:01 UTC
Hi Sarath,
Can you please add W BOO parameters calculation withing pyscal. It only needs to import gsl_sf special function python library to calculate 3-j Wigner symbols.

**Issue**: Still BOO parameters differ for unit cell and supercell of same BCC structure. I have attached here the results. Is it due to POSCAR file formats?
Regards,
Narendra Kumar
JNCASR, Bangalore

[332.vasp.txt](https://github.com/srmnitc/pyscal/files/5569063/332.vasp.txt)
[average.py.txt](https://github.com/srmnitc/pyscal/files/5569064/average.py.txt)
[unit.vasp.txt](https://github.com/srmnitc/pyscal/files/5569065/unit.vasp.txt)
[q_unit.txt](https://github.com/srmnitc/pyscal/files/5569066/q_unit.txt)
[q_332.txt](https://github.com/srmnitc/pyscal/files/5569067/q_332.txt)

**Comment by srmnitc** [comment] 2020-11-20 08:38
@narendra8995 Thanks for raising the issue. The W parameters are definitely interesting. I had originally started it here - https://github.com/srmnitc/pyscal/issues/22. I will pick this up in the coming days.

As for the BOO parameters, I will check in a bit and update you. Thanks for raising the issue.

**Comment by srmnitc** [comment] 2020-11-20 09:05
@narendra8995 I seem to get the same answers for q4 and q6 using `332.vasp` and `unit.vasp`. Could you please check if you have the most updated version - 2.10.3 of pyscal?

**Comment by narendra8995** [comment] 2020-11-20 20:10
Sorry for repeating my issue again. I am getting slightly off values in q(4,6,8,10,12) = (0.053,0.527,0.410,0.252,0.397) instead of ideal values (0.036,0.510,0.429,0.195,0.404,) for 3x3x2 size perfect BCC supercell. It works fine for other system sizes (e.g; unit cell, 2x2x2, 3x3x3, 3x3x4, etc.) but the catch is for 3x3x2 supercell. I am not able to understand this strange occurence. Please help me else I have to rewrite the code at last hour to include crystal identification results using ql in the manuscript under preparation.  Surely, I will cite your work since pyscal helped and saved my time.
I updated pyscal but still problem persists.

**Comment by narendra8995** [comment] 2020-11-20 20:16
Hi Sarath,
If you don't face such issues as I mentioned, can you please include one example which calculates all the ql's by reading POSCAR file of simple crystalline metals Al (FCC), Nb (BCC), and Mg (HCP) and check for unit cell as well as supercell of sizes 2x2x2 and 3x3x2.
Thanks and Regards,
Narendra Kumar

**Comment by narendra8995** [comment] 2020-11-20 20:39
@srmnitc , Even it fails for make_crystal command which generates ideal structure. I have attached here test file. For other crystal structures it works fine but strange affection is with BCC 3x3x2 supercell. :)

atoms, box = pcs.make_crystal(structure="bcc", repetitions=(3,3,2), lattice_constant=4.00)
[test.py.txt](https://github.com/srmnitc/pyscal/files/5575955/test.py.txt)

**Comment by srmnitc** [comment] 2020-11-20 23:56
@narendra8995 I have rechecked again, and I am still unable to reproduce the error. As you requested, I have made an example for Nb, Al, Mg and Si. Please check - https://github.com/srmnitc/pyscal_boo_test . The repo has a binder link on readme. You should be able to run the jupyter notebook on the browser. 

We can discuss more if the problem persists.

**Comment by srmnitc** [comment] 2020-11-20 23:59
For the moment, I am going to go ahead and close this issue as I cannot reproduce the error. As for the w parameters it is tracked here #22 . Please feel free to reopen if this issue if needed or contact me if you need any more help with pyscal.

**Closed as completed by srmnitc** 2020-11-20 23:59 UTC
